const dadosVendas = [
  {
    id: 1,
    produto: 'Smartphone X',
    cliente: 'João Silva',
    quantidade: 2,
    valorTotal: 4000.00,
    dataVenda: '2025-09-20',
    vendedor: 'Ana Paula',
    desconto: 200.00,
  },
  {
    id: 2,
    produto: 'Notebook Pro 15',
    cliente: 'Maria Oliveira',
    quantidade: 1,
    valorTotal: 7500.00,
    dataVenda: '2025-09-19',
    vendedor: 'Carlos Eduardo',
    desconto: 0.00,
  },
  {
    id: 3,
    produto: 'Fone de Ouvido Bluetooth',
    cliente: 'Pedro Souza',
    quantidade: 5,
    valorTotal: 500.00,
    dataVenda: '2025-09-18',
    vendedor: 'Ana Paula',
    desconto: 25.00,
  },
  {
    id: 4,
    produto: 'Monitor Gamer 27"',
    cliente: 'Lucas Ferreira',
    quantidade: 1,
    valorTotal: 1800.00,
    dataVenda: '2025-09-17',
    vendedor: 'Carlos Eduardo',
    desconto: 50.00,
  },
  {
    id: 5,
    produto: 'Teclado Mecânico',
    cliente: 'Juliana Lima',
    quantidade: 3,
    valorTotal: 450.00,
    dataVenda: '2025-09-16',
    vendedor: 'Mariana Santos',
    desconto: 0.00,
  },
  {
    id: 6,
    produto: 'Mouse Sem Fio',
    cliente: 'Ricardo Alves',
    quantidade: 4,
    valorTotal: 160.00,
    dataVenda: '2025-09-15',
    vendedor: 'Ana Paula',
    desconto: 8.00,
  },
  {
    id: 7,
    produto: 'Impressora Multifuncional',
    cliente: 'Fernanda Rocha',
    quantidade: 1,
    valorTotal: 850.00,
    dataVenda: '2025-09-14',
    vendedor: 'Mariana Santos',
    desconto: 0.00,
  },
  {
    id: 8,
    produto: 'Tablet Pro',
    cliente: 'Gustavo Mendes',
    quantidade: 1,
    valorTotal: 2500.00,
    dataVenda: '2025-09-13',
    vendedor: 'Carlos Eduardo',
    desconto: 100.00,
  },
  {
    id: 9,
    produto: 'Câmera Digital',
    cliente: 'Laura Costa',
    quantidade: 1,
    valorTotal: 1200.00,
    dataVenda: '2025-09-12',
    vendedor: 'Ana Paula',
    desconto: 60.00,
  },
  {
    id: 10,
    produto: 'Smartwatch V2',
    cliente: 'Daniel Ferreira',
    quantidade: 2,
    valorTotal: 900.00,
    dataVenda: '2025-09-11',
    vendedor: 'Mariana Santos',
    desconto: 0.00,
  },
];

export default { dadosVendas };